#!/bin/bash

export PATH=$(pwd)/ngx_openresty/nginx/sbin:$HOME/.luarocks/bin:$PATH
export LUA_PATH="$HOME/.luarocks/share/lua/5.1/?.lua;;"

nginx -p `pwd`/nginx/ -c nginx.conf -s reload || nginx -p `pwd`/nginx/ -c nginx.conf
{ sleep 1; curl -s http://localhost:8080/test; } &
{ sleep 2; curl -s http://localhost:8080/test; } &
{ sleep 3; curl -s http://localhost:8080/test; } &
tail -f nginx/logs/error.log
