#!/bin/bash

export PATH=$(pwd)/ngx_openresty/nginx/sbin:$HOME/.luarocks/bin:$PATH
export LUA_PATH="$HOME/.luarocks/share/lua/5.1/?.lua;;"

rm -f nginx/logs/error.log
sudo nginx -p `pwd`/nginx/ -c nginx.conf -s stop || true
sudo env PATH="$PATH" LUA_PATH="$LUA_PATH" nginx -p `pwd`/nginx/ -c nginx.conf
{ sleep 1; curl -s http://localhost/test; } &
{ sleep 2; curl -s http://localhost/test; } &
{ sleep 3; curl -s http://localhost/test; } &
tail -f nginx/logs/error.log
